#!/bin/bash

# password='foobarbaz'

Usage()
{
    printf "%b" "Check your arguments.\n\n"
    printf "%b" "Usage: configer package -s state(default:install; install/remove) -p package_name -v version_no\n" >&2
}

check_if_package()
{
    dst_ip=$1
    pkg_name=$2
    pkg_version=$3
    curr_package_version=$(sshpass -p $password ssh $user@$dst_ip -p 2222 "apt-cache policy $pkg_name | grep Installed | awk '{print \$2}'")
    if [ $curr_package_version != $pkg_version ];
    then
        pkg_installed='yes'
    else
        pkg_installed='no'
    fi
}

# check_if_package apache2 '2.4.29-1ubuntu4.5' '127.0.0.1'

install_package()
{
    target_hosts=$1
    pkg_name=$2
    pkg_version=$3
    for i in $(echo $target_hosts | sed "s/,/ /g")
    do
        printf "Installing $pkg_name with Version: $pkg_version on IP : $i\n"
        check_if_package $i $pkg_name $pkg_version
        if [ $pkg_installed = 'yes' ];
        then
            sshpass -p $password ssh $user@$i -p 2222 "apt-get -y install $pkg_name=$pkg_version"
            if [ $? == 0 ];
            then
                printf "\nPackage Install State: Changed\n\n"
            fi
        elif [ $pkg_installed = 'no' ];
        then
            printf "\nPackage Install State: Ok\n\n"
        fi
    done
}

remove_package()
{
    none_package_version='(none)'
    target_hosts=$1
    pkg_name=$2
    for i in $(echo $target_hosts | sed "s/,/ /g")
    do
        printf "Removing package: $pkg_name on IP: $i\n"
        check_if_package $i $pkg_name $none_package_version
        if [ $pkg_installed = 'yes' ]; then
            sshpass -p $password ssh $user@$i -p 2222 "apt-get -y purge $pkg_name"
            if [ $? = 0 ];
            then
                printf "\nPackage Remove State: Changed\n\n"
            fi
        elif [ $pkg_installed = 'no' ]; then
            printf "\nPackage Remove State: OK\n\n"
        fi
    done
}


#Inputs
while getopts ":u:p:t:s:n:v:" opt;
do
    case ${opt} in
      u)
        user=${OPTARG}
        ;;
      p)
        password=${OPTARG}
        ;;
      t)
        target_hosts=${OPTARG}
        ;;
      s)
        state=${OPTARG}
        ;;
      n)
        package_name=${OPTARG}
        ;;
      v)
        version_no=${OPTARG}
        ;;
    esac
done
shift $((OPTIND -1))


if [ -z "${package_name}" ];
then
    Usage 1>&2
    exit 1
fi

# Main invocation
echo $work_dir

if [ $state = 'remove' ];
then
    remove_package $target_hosts $package_name
else
    if [ -f "${WORK_DIR}/bootstrap.sh" ];
    then
        for i in $(echo $target_hosts | sed "s/,/ /g")
        do
            sshpass -p $password scp -P2222 ${WORK_DIR}/bootstrap.sh $user@$i:/root/bootstrap.sh
            sleep 5
            sshpass -p $password ssh -p 2222 $user@$i 'chmod +x /root/bootstrap.sh && sh /root/bootstrap.sh'
        done
    fi
    install_package $target_hosts $package_name $version_no
fi