#!/bin/bash

# configer_readlink() {
#   (
#   TARGET_FILE=$1

#   cd "$(dirname "$TARGET_FILE")"
#   TARGET_FILE=$(basename "$TARGET_FILE")

#   while [ -L "$TARGET_FILE" ]
#   do
#     TARGET_FILE=$(readlink "$TARGET_FILE")
#     cd "$(dirname "$TARGET_FILE")"
#     TARGET_FILE=$(basename "$TARGET_FILE")
#   done

#   PHYS_DIR=$(pwd -P)
#   RESULT=$PHYS_DIR/$TARGET_FILE
#   echo "$RESULT"
#   )
# }

path_to_configer=$(which configer)
# if [[ $(uname) == "Darwin" ]]; then
#   resolved_path_to_configer_bin=$(configer_readlink "$path_to_configer")
# else
#   resolved_path_to_configer_bin=$(readlink -f "$path_to_configer")
# fi
dirname "$(dirname "$path_to_configer")"
